### ISSUE TITLE
Autoupdate setting id to -1

### ISSUE THREAD

**Issue by matthiasAtFernUni** [ewallah/moodle-availability_relativedate#22]
Whenever a course activity is deleted, the autoupdate sets the dependency id to -1:
`\core_availability\info::update_dependency_id_across_course($courseid, 'course_modules', $modid, -1);` 
autoupdate.php line 41.

Setting the id to -1 breaks the course and leaves it unaccessible. 
(Moodle shows the error: error/moodle/invalidcoursemoduleid)

**Comment by ewallah** [comment]
THX for the report.

This is weird, the code written by @sh-csg contains several lines to handle this -1 value, perhaps other parts of Moodle have difficulties with this negative value.

I will write a behat script to try to reproduce the error. Can you provide me all details (versions of php - Moodle - plugin), and all steps you took, so my script produces the same error?

**Comment by ewallah** [comment]
I created 2 new behat scenarios:

- [first](https://github.com/ewallah/moodle-availability_relativedate/blob/main/tests/behat/availability_relative_module.feature#L115) I delete several modules and one section, and [all tests run OK](https://github.com/ewallah/moodle-availability_relativedate/actions/runs/6284149389/job/17065260403#step:19:145). 
- [next ](https://github.com/ewallah/moodle-availability_relativedate/blob/main/tests/behat/availability_relative_module.feature#L130)I configure a section to be depending on a course module, which I delete in the next step. Here also all tests run[ successful](https://github.com/ewallah/moodle-availability_relativedate/actions/runs/6284149389/job/17065260403#step:19:145).

A message is shown to the end user that the module is missing:
![availability_relativedate_missing](https://github.com/ewallah/moodle-availability_relativedate/assets/1324161/33780275-506d-4882-9321-f702274f113b)

Because this warning easily can be overlooked, I added the error alert class.

But a broken course that is inaccessible, I have not seen. So I will need all steps you took so I can reproduce the error.

**Comment by matthiasAtFernUni** [comment]
I replicated the error by doing:

1. Create two assignments
2. Make the second assignment available after the first assignment has been done.
3. Delete the first assignment.
4. Reload the page.
5. Be presented with the error.

I attached some images and the full stack trace. (I hope everything is recognizable despite our Moodle using the german language.)

![relativeDateIssue_0](https://github.com/ewallah/moodle-availability_relativedate/assets/134049816/24a7b981-055e-4748-967e-ba100bf541e7)
![relativeDateIssue_1](https://github.com/ewallah/moodle-availability_relativedate/assets/134049816/66eb68d9-2ff7-4067-b62e-c6fba9fee6ac)
![relativeDateIssue_2](https://github.com/ewallah/moodle-availability_relativedate/assets/134049816/4fe6d515-e58c-48f8-99f6-40f79d3e6157)

**Comment by matthiasAtFernUni** [comment]
`Stack trace:

    line 242 of /lib/modinfolib.php: moodle_exception thrown
    line 2218 of /lib/modinfolib.php: call to course_modinfo->get_cm()
    line 1041 of /lib/completionlib.php: call to cm_info::create()
    line 292 of /availability/condition/relativedate/classes/condition.php: call to completion_info->get_data()
    line 110 of /availability/condition/relativedate/classes/condition.php: call to availability_relativedate\condition->calc()
    line 84 of /availability/classes/condition.php: call to availability_relativedate\condition->is_available()
    line 265 of /availability/classes/tree.php: call to core_availability\condition->check_available()
    line 197 of /availability/classes/info.php: call to core_availability\tree->check_available()
    line 2251 of /lib/modinfolib.php: call to core_availability\info->is_available()
    line 1689 of /lib/modinfolib.php: call to cm_info->obtain_dynamic_data()
    line 1534 of /lib/modinfolib.php: call to cm_info->get_name()
    line 2219 of /lib/navigationlib.php: call to cm_info->__get()
    line 2258 of /lib/navigationlib.php: call to global_navigation->generate_sections_and_activities()
    line 748 of /course/format/classes/base.php: call to global_navigation->load_generic_course_sections()
    line 255 of /course/format/tiles/lib.php: call to core_courseformat\base->extend_course_navigation()
    line 2173 of /lib/navigationlib.php: call to format_tiles->extend_course_navigation()
    line 1538 of /lib/navigationlib.php: call to global_navigation->load_course_sections()
    line 4295 of /lib/navigationlib.php: call to global_navigation->initialise()
    line 832 of /lib/pagelib.php: call to settings_navigation->__construct()
    line 962 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
    line 393 of /lib/classes/navigation/views/secondary.php: call to moodle_page->__get()
    line 216 of /lib/classes/navigation/views/secondary.php: call to core\navigation\views\secondary->load_course_navigation()
    line 890 of /lib/pagelib.php: call to core\navigation\views\secondary->initialise()
    line 962 of /lib/pagelib.php: call to moodle_page->magic_get_secondarynav()
    line 120 of /theme/boost_union/layout/drawers.php: call to moodle_page->__get()
    line 1473 of /lib/outputrenderers.php: call to include()
    line 1399 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 236 of /course/view.php: call to core_renderer->header()`

**Comment by ewallah** [comment]
This is a very interesting error: 

In line 292 the function completion_info->get_data() is called with -1 as parameter.  But only five lines before this code, the plugin checks if the parameter is bigger than 0 (if ($this->relativecoursemodule < 1).  So in line 287 the parameter is >0, in line 292 the parameter suddenly is -1. How can this happen?

To fine-tune the issue, I have some extra questions: 

1. Do you work with a special cache (memcached - Redis - ....)?
2. Do you have other plugins installed that react upon a course_module_deleted event?
3. Do you see the same error in a standard Moodle course format using the Boost theme?

**Comment by matthiasAtFernUni** [comment]
1. We do not use any special cache (memcached, Redis). OPCache is enabled for PHP, but that should be a farely standard setting.

2. Two plugins are installed that act upon course_module_deleted:
- https://github.com/bdecentgmbh/moodle-mod_pulse (v1.11)
- https://github.com/edu-sharing/plugin-moodle-edu-sharing (commit d9c6bfa24e72d33c3456893e8c075fd13a54ab97)

3. We tried other course formats and the error remains.

**Comment by ewallah** [comment]
At the end of September, I added an extra [try...catch](https://github.com/ewallah/moodle-availability_relativedate/commit/da8f7dcf811b56f757c72d09d3b5d1c68daf391e#diff-68cf389f000a345b3f9a3fa48127930c19fe5ff4e108d37b835754cc2eef0c86L298) block to handle these possible exceptions.

Do you still see the error with [v4.0.9](https://github.com/ewallah/moodle-availability_relativedate/releases/tag/v4.0.9)?

**Comment by ewallah** [comment]
The plugin seems to work fine with mod_pulse.
The edu-sharing plugin is throwing errors during backup/restore.

I created a new branch with both plugins (and sub plugin) [installed](https://github.com/ewallah/moodle-availability_relativedate/blob/ewallah-issue-22/.github/workflows/main.yml#L23). 

[PHP has errors:](https://github.com/ewallah/moodle-availability_relativedate/actions/runs/6903075987/job/18781044335#step:17:17)
`Debugging: Exception encountered in event observer 'mod_edusharing_observer::course_restored': Table "Page 1" does not exist
`
[Privacy has errors:](https://github.com/ewallah/moodle-availability_relativedate/actions/runs/6903075987/job/18781044335#step:18:47)
`core_privacy\privacy\provider_test::test_all_providers_compliant with data set "mod_edusharing" ('mod_edusharing', 'mod_edusharing\privacy\provider')
`
[Behat has errors:](https://github.com/ewallah/moodle-availability_relativedate/actions/runs/6903075987/job/18781044335#step:20:149)
`Exception encountered in event observer 'mod_edusharing_observer::course_restored': Table "Page A1" does not exist
`
But I do not see the error you mention (An error that cannot happen because 5 lines before this coursemoduleid was not -1 but a value greater than -1).

Perhaps you can contact the guys from edu_sharing and mention the issues?

**Comment by ewallah** [comment]
FIXED!
