### ISSUE TITLE
[v4.2.2] Request to update the changelog

### ISSUE THREAD

**Issue by danowar2k** [ewallah/moodle-availability_relativedate#29]
Your changelog seems to be outdated: https://github.com/ewallah/moodle-availability_relativedate/blob/main/CHANGES.md

Could you update it (or add a notice where the current changelog is)?

**Comment by danowar2k** [comment]
Thanks!
Did you know you don't need to release a version just because you did some code cleanup and/or changing the github action?

Also, the changelog now talks about v4.2.3, but you created a tag v4.2.4 ...

**Comment by ewallah** [comment]
The change log was generated while trying out new log creating software. No idea it automatically entered a new tag, and my version file was not submitted, so I ended up with a incorrect change log and version file. I have to review my multitasking skills...  But see it positive and think I'm also testing out a bit the auto "Releasing in the Plugins directory" script, what happens if I submit wrong values?

I follow more or less general Moodle support:  general support for 4.1 ended on [11 December 2023,](https://moodledev.io/general/releases), so only when there is a security issue with this plugin, I will have to create a new version for 4.1. Currently I only run instances that support PHP8.2+ (general support for PHP 8.1 ended on [25 Nov 2023](https://www.php.net/supported-versions.php)). How else can we force users to stop using unsupported software?

**Comment by danowar2k** [comment]
Oh I fully support stopping users to use unsupported software, but Moodle 4.1 will have security fixes for a while, and I was sad that we'll only get the new plugin release once we switch Moodle versions (which will maybe be in half a year)...

I don't automatically generate my changelogs, I always use the same format and add lines when I close an issue (or let others add an appropriate line):

```
## TAG (RELEASE_DATE)

### Fixed

- Some amazing fix fixes something
   - Solves/Helps solve/Done during #ISSUE_NR

### Added

- etc

### Changed

- etc

### Removed

## NEXT_TAG (RELEASE_DATE)
```

Of course until now I've only done changelogs for work plugins etc.

**Comment by ewallah** [comment]
Should be up to date by now
